version: "3"

services:
  apache:
    # You can choose between build the image by yourself or use
    # the image already builded. Just comment one line and uncomment the other

    # image: viniciusbig/cakephp3:v1
    build: .
    env_file: .env
    ports:
      - "${APACHE_PORT}:80"
      - "${XDEBUG_PORT}:9000"
      # - "35729:35729" # live reload
    volumes:
      - ${PROJECT_ROOT}:/var/www/html:rw,delegated
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      # - ~/.nvm:/var/www/.nvm
    environment:
      XDEBUG_CONFIG: "remote_host=localhost"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db

  db:
    image: mariadb
    env_file: .env
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./.database/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    ports:
      - ${PMA_EXPOSED_PORT}:80
    links:
      - db

  mailhog:
    image: mailhog/mailhog
    env_file: .env
    ports:
      - ${MAILHOG_SMTP_PORT}:1025
      - ${MAILHOG_HTTP_PORT}:8025
