#!/usr/bin/env bash

if [ "$2" == "clone" ]; then
  git clone https://github.com/viniciusbig/cakephp-docker.git $1 && cd $1;
fi

git config --global core.autocrlf false
git config --global core.eol LF
git config --global core.fileMode false
git config --global diff.renamelimit 5000

sudo chmod -R u+x ./*

# docker-compose build
docker image pull viniciusbig/cakephp3:firsttry

# Changes by SO
# if [ "$(uname)" == "Darwin" ]; then
#     echo "Running on MAC OS"
# elif [ "$(uname)" == "cygwin" ] || [ "$(uname)" == "msys" ] || [ "$(uname)" == "win32" ]; then
#     echo "Running on Windows"
# else
#     echo "Running on Linux"
# fi

if [ ! -e src/index.php ]; then
  echo "<?php phpinfo();" > src/index.php;
fi

if [ ! -e .env ]; then
  cp .env-sample .env
fi

chmod -R 777 src

bash start
